# Generated by Django 3.0.6 on 2020-05-26 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfriend',
            name='recipe',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
