# Generated by Django 3.0.6 on 2020-06-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo',
            new_name='gallery_photo',
        ),
    ]
