# Generated by Django 3.0.6 on 2020-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200626_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
