# Generated by Django 3.0.6 on 2020-06-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200630_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='memberId',
        ),
        migrations.AddField(
            model_name='goods',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Orders'),
        ),
    ]
